targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/core/di/injection.dart
      auto_route_generator:autoRouteGenerator:
        enabled: true
        generate_for:
          - lib/core/router/app_router.dart

